name: Upload HTML
on:
  push:
    branches:
      - upstream
  workflow_dispatch:

jobs:
  upload-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: upstream
      - name: Transform USFM
        run: npx --yes @openbible/usfm -o dist *.usfm
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - run: rclone sync --progress dist static:bibles/en_ust
